apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-replicator-crb
subjects:
- kind: ServiceAccount
  name: secret-replicator-sa
  namespace: secret-replicator
roleRef:
  kind: ClusterRole
  name: secret-replicator-ca
  apiGroup: rbac.authorization.k8s.io
