apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-replicator
  namespace: secret-replicator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-replicator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-replicator
    spec:
      serviceAccountName: secret-replicator-sa
      containers:
      - name: secret-replicator
        image: kiwigrid/secret-replicator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRETS_LIST
          value: letsencrypt-wildcard-cert
        - name: IGNORE_NAMESPACES
          value: kube-system,kube-public
        - name: SECRET_NAMESPACE
          value: letsencrypt-wildcard-cert
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
