apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: minio
    labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: storage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bj9efiYPWMxzB6urvfpq5oMZ7iaml0rZHb/rixvUdo5RTTYySkDpeMTw0n6LWoH2cWXabV5H3jUQ35fcNh+XvsXqmnQGWLgRtOvXw1LfuD90Vq0AkA==,iv:84fZIbrt3tIbRIufezX4KPULyTGXftMfdHCqj8ue79g=,tag:1aczHotmesK7kuLpJGQFEQ==,type:comment]
    #ENC[AES256_GCM,data:x/0Qp1CNI/RWJSwOdSWrY2JyY195IZJSDEqS2elj1BGxi83WP6uLG/2Ls+HLA5gp8mokGc2OlaBAmVv8QaE7ZAVZh+OI4g==,iv:1tvYiJyB7FMhGcvufi9qcz9DB8l0VPIr4eRyJqBpyGw=,tag:JF7xUuKnt2Whhn9rqhIWbA==,type:comment]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:I8P1kTQ=,iv:MdfYer50na1i6lxFa9jAsTELuK/LYNrgHBY4EoM/T78=,tag:uCIYDTPDutDJ7er4uDsLQQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:rc9kHVduLXv2J4jV,iv:NcXcXdJ9vlg5JW9onMmU9IcQ5wQqSZyFtHeK5V02q3M=,tag:k+CNG+2Bd3SUFHNf1Y3f/g==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOTBTQWd2cnJQSDBpa002
            QjdHM2c5c3hQK1JTb0NLdDlXRHVQUTc5RDN3CjBGZ0EwNExQY0NFNEhLdE1DMFNE
            cnczVnRVQWFaUEhIRmk0aDIxQWdPQ2MKLS0tIDFGZjRZY04vRnNrejJQbG84dlRy
            QVZKOExHWGdMNGExeW5wNkZ4YXBGL1kKbiahbPQnwy2f8S/XiwGkssKTUqJprmiQ
            C69io7GF+sfMdAhRG+mGlIUbAUIIHrh/wWMabJR/X0LGSjSQPZ/O9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T16:31:26Z"
    mac: ENC[AES256_GCM,data:Y44EjMSSWRqTb5GtppCwXYfGL2XnvMqvVuFSyTpY5ibD7XQMLr19gHF2NSFqEXqMrpUcX9TfDAx4hclhbNtNHs1qkP/Hb+7JIPfVmxuu8q2iDb/B3jP2GfT8Wtxx70Au1AZVMuDP3XEkYukGCD7fkyhF3BbgomnOZVYWnQ/lReU=,iv:QyWdXiSNMF8GomiOwFUQOBC8z2RNTjU965ZUuisSRkw=,tag:We4M22rCjpiBcJD04PU4Xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
