apiVersion: v1
kind: Secret
metadata:
    name: minio-studybuddy-provision
    namespace: minio
    labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: storage
type: Opaque
stringData:
    #ENC[AES256_GCM,data:shL1TrfmokY/PWhg5gaau8MfdcywGJcbWg3ikSmdrsLl,iv:tTHbPKX3GZ3n7AXrAhF0jjWdghrrkXIvTzLURj5jttM=,tag:r03nNLDM1IMkH1Hm6GX9Rg==,type:comment]
    #ENC[AES256_GCM,data:dPxdjlOTpi1y7B0Eg4j6nTveQKSfG7KW+yn2pR70XUcwiC1BR3iDB99VAdlodi2aMjW6Yv/fHDKJMUTBQM4LjgLWWQ==,iv:W9aY4Gzitj8qJAswMOFt+KGJ2gK47LV624aGJDV/OfE=,tag:IVJJ1cAJgFxlym7Rt50nLg==,type:comment]
    MINIO_STUDYBUDDY_ACCESS_KEY: ENC[AES256_GCM,data:GnMDrO5QPpi1qg==,iv:72EkLiWh7fc8DvuMSPHPWS2O1kGC3VMcodcsyy8y4tM=,tag:wlD66GgMlAMGrDePcnD2UQ==,type:str]
    MINIO_STUDYBUDDY_SECRET_KEY: ENC[AES256_GCM,data:GCprqesxxUcPLY0x,iv:C1fxy4zptL6ucCQQEV7pdpKytXl4hh0EPvZBIQkRIHM=,tag:2PxLHvTk1Sy+rYXTPFCP8Q==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZUZMOXNOc3JvNVQ0ZjBo
            eitXYTVDejlpeSs3VGRtaDlYcVRML1daclhZCjN5d0ZkbHlhQS9kU21EM1N2TU5X
            SVBJSjExRENmYzhlUDltN1AwSldRK3cKLS0tIHdSWVNXUk56N3RMSEJzandaK0lD
            VmR6YndkMVhxRUtRZWxUWmh5ZjNVTlEK2Na4QakCkE7wj0gyy1o+REZs4ZRDq3vE
            Qs2SHY07hazBZyfw1LskUSz0N8H8zk7bIUznrNxJzqPRPHuQ7Gk3bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T16:31:36Z"
    mac: ENC[AES256_GCM,data:OwXY38gCiOzQQayghU9URxuMeVjhR9+ZEhTsMJ5ci0H7oBgVouBjXQp889VxqNUetGA/QLEhIu1pkggUpFpSON9VSVpf4mmr0bz+rOHIOjKS/DtXhhwtN25xshI8duLftJzIXqgQ/lvO3Lhp16EbjxormwDpcmqz1lnrEgl8/gE=,iv:yZp1UStIPnM1EKZznN0qMXfjL510ndIZxVuriQfVhFs=,tag:DmLLNo9prptzcMlkdRQHbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
