apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "4.12.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: nginx-ingress-controller
  interval: 15m
  timeout: 5m
  values:
    controller:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      replicaCount: 2
      service:
        type: LoadBalancer
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true