apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres
    labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6LAkET+IcvNyztgjcV+RsH0MuNa1qx61SJnPexn1/9MYKcSbpJViOY4wqsdItGtrLCH6hbzB8r4w9lxUXombhBLAT7d5USjfU5DvyX0=,iv:3DX9PmjIleofG5swxmFgBDJS2jeodMtD1XD9vL/WpdQ=,tag:Rsi+iK8i8118gN/mjOfRpw==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:kNG4KYaCCq0=,iv:wIjFhqAX2FD3VOmGbMnXgY+0WU8CFPq3zWcq2a7D7F4=,tag:85rXNhaVaACqrWouFuowvw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:FbOB3FOuosfQ0gL/,iv:iE8VTu6NfrY0kmGXWKbVcsJtPzHj3WPELJ4psMvPWuA=,tag:lAPZ1i954be415cJHijYfA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:TwGg9Z8J0cM=,iv:/hAUJt63MZ7Lw0aq8TdYNzWKjFFFJpb1r+2uGGEcvXw=,tag:til/C0YScDWKIvZC/qeJww==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVWtSYmpxN2JBRytuTjBo
            MlJQS1FVTE0vM1kwampzS1JiZGRNTkZ3M2xRCmF2Y1d3QS9xSDZjTnVCOW1SUTI1
            Z3gxT0dLWFZFZVlWQUpUVVdXMVdLUGMKLS0tICszWlBDbk91ZW1rNHB1UlJTTFdK
            czhDaWQ2RjVPWTUyU3NZVE1LM25OdzAKjZkyE/lX6C+yvdtdE0836FqZDsypYlPA
            FYC8PmZqv0y4kfa8Ctha5+XYbyH+6e7sGoaZ51JFuASgDn2GH1VwKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T16:31:07Z"
    mac: ENC[AES256_GCM,data:tkWCS8WyuHBuUVXbiEcFS1mvTmEwXSZ3pMasSs7nZ9WQhGwEI/zQ++yj+PXQKGSSBgChNmXlVs8pt1n1TnYuOjC5awV465KwYliXel9RP0+WRw5oMzn//6HemarREyyxbBui4Hxf0E8L9izokAal3biQv5go1Up6F+nEa8ADZBo=,iv:0GVjkcNLOyoljirao29KcoqB4POAZQrp8ZLclpBP/g8=,tag:tzCPhAM3Ehh7rDvWJVVjMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
