apiVersion: v1
kind: Secret
metadata:
    name: cognitia-api-livekit
    namespace: cognitia
    labels:
        app.kubernetes.io/name: cognitia-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: cognitia
type: Opaque
stringData:
    LIVEKIT_API_KEY: ENC[AES256_GCM,data:4OzuxB8/8ByNOoiw3YW2uA==,iv:PPbP3tLaj1vpZ/qbiWvs+1Ep9/fL9FoWCjBVKYMrimw=,tag:/yIRz7mvvhxWTGJC5KhYVQ==,type:str]
    LIVEKIT_API_SECRET: ENC[AES256_GCM,data:adfD+/0atKvnwPwTPOIbGLFkyoGaWAQaT0boXzSV1PiM7CkVGZpXcE3yqGVWrYGhPnnlrEj+Gh3LZtYMMbu8Rg==,iv:O49gBTbcrl6cLTowxWbrHs3k5prwpYxAgMcfT2ZTiC0=,tag:66BJR6l47pH58ucWXEt4NA==,type:str]
    LIVEKIT_URL: ENC[AES256_GCM,data:nsBtsGKrAGKy/uUY5Tl6AzgfHQdR9BHUZKVZQgONLw==,iv:8JPpRn3v1ZmKYaAawqHzo2YHlEM9hjczjZpYboPrS/A=,tag:iAD/n1MsxPuKkdoBzCPCFw==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWUpiVi9JVEZlblNSSkU0
            T2s5bzR4Wm1xdW13M0lsbmNMYUpjUStrK3hzCllvcGdwVVJXUFc3MEdNNUVHeEcy
            TUdMYUtqdzExU2hEbGpWeW5qekxyR3cKLS0tIDFaYVZzVUpxbit3WTdtR24vSnRa
            VitzVUpKS0Jwbi9XVmNISzlyNVROZVkKtQ0ZlljZavJZIT0KYbLStL3NsuO0CHDT
            exE3+gaV6aBeGqETfuvrZhRjnbaP7TuvgXZQmlhXMMBwdJh5jhJYvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T15:36:29Z"
    mac: ENC[AES256_GCM,data:iil99sh0762osXN2JUgkyCd8FGjhRWAUdTIHUpgTJIx/74eKCWjfIT61UGiqzm7AsZNUa9lP/TtGj2yPRDlgpb4XntS3gBL2r44clRQVdWQ1iXhNn1Bo6CwGUmIMhkeKoUjSO/QNbCcY5ZtsX2xyvQSfU3jF7I0ZgQKK3mWeXzQ=,iv:bEfHasXr33Sp3XMWJ2Jvga7JY0blwUw7Zm6kS3h3Ew4=,tag:qrm93UZQsVFqYhwXyfhHNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
