apiVersion: v1
kind: Service
metadata:
  name: cognitia-api
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cognitia-api
