apiVersion: v1
kind: Service
metadata:
  name: cognitia-auth-lb
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: cognitia
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cognitia-auth
