apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cognitia-iberu-me
  namespace: cognitia
spec:
  secretName: auth-cognitia-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "auth.cognitia.iberu.me"
