apiVersion: v1
kind: Service
metadata:
  name: cognitia-auth
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cognitia-auth
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
