apiVersion: v1
kind: Service
metadata:
  name: cognitia-livekit
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-livekit
    app.kubernetes.io/component: livekit
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cognitia-livekit
  ports:
    - name: http
      port: 7880
      targetPort: http
      protocol: TCP
