apiVersion: v1
kind: Service
metadata:
  name: memory-addon
  namespace: cognitia
  labels:
    app.kubernetes.io/name: memory-addon
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cognitia-memory
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: memory-addon
