apiVersion: v1
kind: Service
metadata:
  name: memory-redis
  namespace: cognitia
  labels:
    app.kubernetes.io/name: memory-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: cognitia-memory
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: memory-redis
