apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memory-personas
  namespace: cognitia
  labels:
    app.kubernetes.io/name: memory-addon
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cognitia-memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
