apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: cognitia
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cognitia-memory
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
  selector:
    app.kubernetes.io/name: neo4j
