apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data
  namespace: cognitia
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cognitia-memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
