apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cognitia-postgres-data
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cognitia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi
