apiVersion: v1
kind: Service
metadata:
  name: cognitia-postgres
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: cognitia-postgres
