apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: cognitia
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: cognitia-memory
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
  selector:
    app.kubernetes.io/name: qdrant
