apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cognitia-redis-data
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: cognitia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
