apiVersion: v1
kind: Service
metadata:
  name: cognitia-redis
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cognitia-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
