apiVersion: v1
kind: Service
metadata:
  name: cognitia-web
  namespace: cognitia
  labels:
    app.kubernetes.io/name: cognitia-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: cognitia
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cognitia-web
