apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  suspend: true # upgrade failed with context deadline exceeded; metallb is deployed and functioning
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb