apiVersion: v1
kind: Secret
metadata:
    name: studybuddy-api-secret
    namespace: studybuddy
    labels:
        app.kubernetes.io/name: studybuddy-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: studybuddy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:K2lKJbpAVSn3A+B94SEDPbSNTqVOCHvOTT/knwsp7FQrDXQQyklGG306jhTKAXS48oks2+KTkbGTaW1w0hJ6uh+1A34aqlOqLNpuT431UKGYlq3WYm0x4xShdX3v+g==,iv:zC0HBzpeTpQx1xL9ll7g8savI+4MTlj4GTl0lAhoubw=,tag:90ZViXhSe38BBWt7LEm1nA==,type:comment]
    #ENC[AES256_GCM,data:/RzRJp+2IRktv95fIj9Mz4xXWet4HuwHzEwK2SXwW+SmW25DswpGiHEUqtB+lkw18G1GMKNjghqmN9EiTEsCKhYMGd3IJJQ6MeuxMvayxtrrdjEJ+FGO92Nl+w==,iv:rg2U9vsNiWwA8LnjrD7DJhJfJYTVFBdmUDH6spJaeRw=,tag:Bb3RrxGtymauwDMxwswKlA==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:we3UUFmp2lPEdg==,iv:qK3mx2Y80YEk5G+NB5fb3CipMekF5BkE0O1mRHRdAZk=,tag:llyxVjWxMrVTIhp6TwpI3A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:NcxUT72qXjHhkO8o,iv:ckMPnupD776WvaPc6Q5CPmY/K545nPNT55Xp/D6yN2M=,tag:1TmF3uSTSkf2dL0EMHxQtg==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:ZShg9uI6vaUK/uTsM2dUhk2k00CRdpKQPwF41IcVgPfojMHvU0/lUUEaPxQmVU2IZZChd1/cDkwvCpyN41RmywVhPgzSr99fUxoJroou9xFXGYzgb23W2FczDOrJNaVgfEhpMKDtZU9nsqTwikt5m8IX43AOwDSw7BZDZ61UWV1ijVsr9SA1bzspmlEfanCae9IKhc270rBk+2RBAmnwW6onUwM=,iv:tGYXeVIE8wifrMS22bnVjIoNoTIxEvZNCGOS15juUcg=,tag:OMSLAPkNwfud9xt/B8jnvw==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdVdUSG41YXNsRlFGdVhn
            TFRoL1prS3p2Sy9QcmhGMm43cDcwajNZWG1ZCnlubDJuMFhsVGFncDR2Tk1zQ1Zu
            SUEzNnhCakxpVlBYV3JOb0dhK1h5ZTQKLS0tIFNqVE1NSUhIUm4vVURZd25nS3hH
            RitTUXl2L1hYSzFxQkVsWFFLd1ZCaVEKCC73GYLrYZZnJqqiOLrFvgQbH4ao0oyk
            SZlG4o2w5R0/YVyerqfLdmt9EtUEdVrCPBpAiTTtKf2EJu5aoUuKPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T14:16:28Z"
    mac: ENC[AES256_GCM,data:MLYbDkU/tfafNReOswUyYDVhlE9uy06ogHKY+8UZw2icPcdqV3wtTCuFOvVY3BIAPHM2HjNDQuc9M90Hu05pNh+GtqlCdAG0d1ZpKm8xpckX7ZrbFmRh2DGGNtNqA7YGAySNZYafnxejM49O96vB++TXt6IDBO0yvcsfLvCtiL8=,iv:mEAq96qzGZMRSb/k3+kjUoEq1ibXiBuCSFkxTO0+NAg=,tag:Sz3Uoh2KAgwGF5l0jKSKgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
