apiVersion: v1
kind: Service
metadata:
  name: studybuddy-api
  namespace: studybuddy
  labels:
    app.kubernetes.io/name: studybuddy-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: studybuddy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: studybuddy-api
