apiVersion: v1
kind: Secret
metadata:
    name: studybuddy-api-secret
    namespace: studybuddy
    labels:
        app.kubernetes.io/name: studybuddy-api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: studybuddy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:K2lKJbpAVSn3A+B94SEDPbSNTqVOCHvOTT/knwsp7FQrDXQQyklGG306jhTKAXS48oks2+KTkbGTaW1w0hJ6uh+1A34aqlOqLNpuT431UKGYlq3WYm0x4xShdX3v+g==,iv:zC0HBzpeTpQx1xL9ll7g8savI+4MTlj4GTl0lAhoubw=,tag:90ZViXhSe38BBWt7LEm1nA==,type:comment]
    #ENC[AES256_GCM,data:/RzRJp+2IRktv95fIj9Mz4xXWet4HuwHzEwK2SXwW+SmW25DswpGiHEUqtB+lkw18G1GMKNjghqmN9EiTEsCKhYMGd3IJJQ6MeuxMvayxtrrdjEJ+FGO92Nl+w==,iv:rg2U9vsNiWwA8LnjrD7DJhJfJYTVFBdmUDH6spJaeRw=,tag:Bb3RrxGtymauwDMxwswKlA==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:we3UUFmp2lPEdg==,iv:qK3mx2Y80YEk5G+NB5fb3CipMekF5BkE0O1mRHRdAZk=,tag:llyxVjWxMrVTIhp6TwpI3A==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:NcxUT72qXjHhkO8o,iv:ckMPnupD776WvaPc6Q5CPmY/K545nPNT55Xp/D6yN2M=,tag:1TmF3uSTSkf2dL0EMHxQtg==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdVdUSG41YXNsRlFGdVhn
            TFRoL1prS3p2Sy9QcmhGMm43cDcwajNZWG1ZCnlubDJuMFhsVGFncDR2Tk1zQ1Zu
            SUEzNnhCakxpVlBYV3JOb0dhK1h5ZTQKLS0tIFNqVE1NSUhIUm4vVURZd25nS3hH
            RitTUXl2L1hYSzFxQkVsWFFLd1ZCaVEKCC73GYLrYZZnJqqiOLrFvgQbH4ao0oyk
            SZlG4o2w5R0/YVyerqfLdmt9EtUEdVrCPBpAiTTtKf2EJu5aoUuKPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T22:20:58Z"
    mac: ENC[AES256_GCM,data:jBnMNpkJ8e8TbrdADj4RXerhi/KNPlVi9h0RN/umVEEsiWP0PDg2ozSjyIeNMM8zMSIRuRC4WE8E66Hrgxgq6MpuDHo1tbbxnjGdM3yZV93P8hSp+u40TtEVgkxq6GB/2OiqH9CElhO5Rruv2Q0rh/lxGuwsssbV9mCqOQm/IFs=,iv:LwBPhKCBbuOUMIlJF514H9d5RDPsbDt9CI4iyC4GELI=,tag:GhmZeR1A7tgjSjpnMKtT9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
