apiVersion: v1
kind: Secret
metadata:
    name: studybuddy-groq-secret
    namespace: studybuddy
    labels:
        app.kubernetes.io/name: studybuddy
        app.kubernetes.io/component: llm
        app.kubernetes.io/part-of: studybuddy
type: Opaque
stringData:
    LLM_API_KEY: ENC[AES256_GCM,data:F3vsDQrlHzvKx6jBxA+ZGr+OUCUZSrxyWAJ9L84SucGZi8uFEMx5I+je2CpNiALevCL7lZifxeI=,iv:dgCHQuAEkm8zh95V26tXOGH5VFCXXAVtmDH7suqIC1c=,tag:6MhD1Vm/ypViy6MtCgypgQ==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdm0wN3dCc0U3VGRqb2I2
            MjFtVU1nbTVIS290bU5ENXE4bU04NUk2eFZnCm43VEFJOG0rQ3hrdHFYWmFNWENV
            c2U4UTNoMTdqSThLa1cwMkluaXJ3UnMKLS0tIEF0MFNXdWV6blZ2YTdKRmNkdHRJ
            UzFFRDZZRTg3VElDSWVMRGhSYzRnRlEKsD8BnMb8Z4JD+CcRxQV5d3xTthGl3pJ9
            bB+n6dIk8cx6OYNn+aX1Z0UkNMux203mnJ/2rNJNQfZvn+19Eml4Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T15:17:16Z"
    mac: ENC[AES256_GCM,data:prMsuP134LLdVh8AzbwNOzqYqPjomkEXEJVCt2UgYKNIN/YDbY+o+7cUxR4w4aU2yddW/wgxfX4lX+qtlFrEInT17+EpT8/N06h9mag35c8+bCDmCqZhf5yTxBFumwv1Ju+62zRhQgZCsHKda6np8dVS8a8i1dukejH0Do3IwyU=,iv:syMKmDXzfQm4A4mct4B4RvHdJj8kvGIfVVLzXuvedYA=,tag:n+OiP3kcIt9r5bLI7q1NRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
