apiVersion: v1
kind: Service
metadata:
  name: studybuddy-web
  namespace: studybuddy
  labels:
    app.kubernetes.io/name: studybuddy-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: studybuddy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: studybuddy-web
