apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  interval: 15m
  timeout: 10m
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
      service:
        type: LoadBalancer