apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  interval: 15m
  timeout: 5m
  releaseName: nginx-ingress-controller
  targetNamespace: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      admissionWebhooks:
        enabled: true
        patch:
          enabled: true
      metrics:
        enabled: true
      replicaCount: 2
      service:
        type: LoadBalancer