apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: auth
type: Opaque
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:6C1p3mU=,iv:OsWSlM9c0SKMskjnp8h/egngVNFKUCPy+iQUMz+N3wc=,tag:Vq+/kkcwjSbIhYfpyt5Qyg==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:pJzK0Qq0AgRWFsH7,iv:/tZGdq4srDyS4yMsH4RkLOieNO45Z4EFcEVMKQruWz0=,tag:Tw0oIsXa6WK7xVaymDQ5og==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTVhsSGR0RnZxNWhKcm9S
            eGlNKzBMUGpCS25yaFB4alhqckYyYlJZTzJNCko0Um5MWlZzSHM0YVRGNXFTaTdQ
            bW9UcEk4SEVHZTVEeDNQRFRKMTR0dlkKLS0tIEltbnpIazd5TDliSFhuemUrOHR3
            K0h6Q1l6a2w5bHdxaFdnZlRVRnNUdUUKMkO2P7050kH6KnFtzqGSayTLmZDVFAld
            tYkPZ5st25+gby/j1YGuPhjamHbCTGYLSVD0WXnU3gwUZzHnoRUioA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T16:31:45Z"
    mac: ENC[AES256_GCM,data:948XTHis7aFm4AA6aZL07/9DcyS5A0hRMqH18HA3gB1MJM8dTVBcGj1KtZanOSdnZ7A9iDYufWeMlx1jn5rh16DY9NQnh4CRrs+033ktAr5I/g01d4sMrdrOxRkpH5yweKkbCoR4VdE2ZimowJwSS7ZOoTC2ncty3vLerfcp1iU=,iv:m6ezWtclw4l47TbBIkqKzk0PGDdrInqFhgjsbIOXl18=,tag:3UDFJtG5B0sygq1LeGqghg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
