apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: auth
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: CHANGE_ME_keycloak_admin_password
