apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: ingress-nginx
  interval: 15m
  timeout: 5m
  values:
    controller:
      fullnameOverride: ingress-nginx
      # hostNetwork removed for Cilium
      dnsPolicy: ClusterFirst
      replicaCount: 2
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          # If using MetalLB:
          metallb.universe.tf/address-pool: default
          # If instead using Cilium LB IPAM, comment the above and optionally:
          # io.cilium/lb-ipam-ips: "10.0.0.50"
      metrics:
        enabled: true
      admissionWebhooks:
        enabled: true
        certManager:
          enabled: true        # use cert-manager-managed webhook certs
        patch:
          enabled: false