apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: newt
spec:
  interval: 15m
  chart:
    spec:
      chart: newt
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: flux-system
  values:
    newtInstances:
      - name: main-tunnel
        enabled: true
        auth:
          existingSecretName: newt-credentials
          # Keys match the default: PANGOLIN_ENDPOINT, NEWT_ID, NEWT_SECRET
        upstream:
          # Pointing to the Ingress Controller to handle both HTTP (Jellyfin) and TCP (Glados)
          url: "http://ingress-nginx-ingress-nginx-controller.ingress-nginx.svc.cluster.local"
