apiVersion: v1
kind: Secret
metadata:
    name: newt-credentials
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:vCyGxEn5D9Zboy7dH1dCDQcX36CFKCc6xg==,iv:I0HlO1Txo7HRL/GSiAgbjwZDY9wUq9hOiWsf8ZApbEA=,tag:UDMCvui/OlHEEO6ZcFewqA==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:o5Ar0Abjg3K/rfOl+5hS,iv:6ddhv1dY0ZlZpjoEB9e5oKJ3XXxfjKJj5kzlw15yE+o=,tag:BLNpqSXYTt5W68Y1ibY4Sw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:SN6pyglvbGLWvLbA2dsW/ve2lkoHBsUyAyqfeZIPt3OCgLiD29/a6cHsolH1OEtS,iv:rYUQtn3BLgyALco8geDlVkemRINr5BmImyhpXOKSS5E=,tag:WuS25EzHvYMvw2nguu3gHg==,type:str]
sops:
    age:
        - recipient: age1n39wyrdgfj9ta5s7fwj786d4jjjhc90aw7f2ffqsmg794vme6swqtd9jca
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSlhBY0hNME1DSkxWT3VM
            SWg1R1RSSHp2MlE1T01SSVZ5TG1pUkc4aXpZCmJvUG91QlFaM09IZ21TL29ROVZj
            d0RiQVBSb3p1ZG5qdGs3RVprcFlxZ0kKLS0tIFgvSkNvdWp2WTJBM2w4eWhac0lm
            Um82RTdrMmR0QnczZTZTWG9aaHF3UFkKwOnjk6bptLWP0B2cn4RWhviatx+9BjBm
            WHkA4sIYyem9VVyzcuV0k5i7nFd7hTMLWlhIRBYoSn7Jv181RGtTqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T15:43:32Z"
    mac: ENC[AES256_GCM,data:fH2ZSuhrddrt4xuqwVQgNd9mjn9np2CX93n4+BsqZNbcpis54haBLB/zdRVzMopL6cg+wpFGo8CtK5SjNKzBJeVx+4lrs44GA8fnab8RQs0ylGOGibEYhcy/ETNGh5Oca0DLZBu3GP3ovluIxbDzrlFzJh3rwVxyNsVXhLY3jf0=,iv:7pvmJpQwtUnBNJkpoTP1Fl7M48cSi4323UGnxfb2pjQ=,tag:UrMBdLAQMG+rgpr8wBBXjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
