apiVersion: apps/v1
kind: Deployment
metadata:
  name: newt-tunnel
  namespace: newt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newt-tunnel
  template:
    metadata:
      labels:
        app: newt-tunnel
    spec:
      automountServiceAccountToken: false
      containers:
        - name: newt
          image: fosrl/newt@sha256:85e51cec74001295ea84998aae682c58521ee5b950663792dec98973a52ed840
          imagePullPolicy: Always
          env:
            - name: PANGOLIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: newt-credentials
                  key: PANGOLIN_ENDPOINT
            - name: NEWT_ID
              valueFrom:
                secretKeyRef:
                  name: newt-credentials
                  key: NEWT_ID
            - name: NEWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: newt-credentials
                  key: NEWT_SECRET
            - name: JELLYFIN_UPSTREAM
              value: "http://jellyfin.media.svc.cluster.local:8096"  # adjust port if svc.port != 8096
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi